services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 10s
      retries: 5
      start_period: 30s

  # todo-example:
  #   build:
  #     context: ..
  #     dockerfile: build/package/Dockerfile
  #   container_name: todo-example
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - ../.env
  #   restart: unless-stopped

volumes:
  postgres:
